# Generated by Django 4.2.10 on 2024-02-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackkey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='entry_id',
        ),
    ]
